name: Build Docker Image and push to GHCR

on:
  push:
    branches:
      - main
      - backend

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Build Docker Image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Log in to the Container registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push (backend)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ghcr.io/tamarawoessner/anwendungsentwicklung-projekt-backend:latest